image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: |
      dotnet restore quince.sln
      gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script: |
  dotnet build
  dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets NetworkedPlanet.Quince /p:Version=%GitVersion_NugetVersion%

test_script:
  - ps: |
      cd NetworkedPlanet.Quince.Tests
      dotnet test --filter "Category!=GitWrapper"

deploy:
  - provider: GitHub
    description: 'quince $(GitVersion_SemVer)'
    auth_token:
      secure: waxwfb392oVPzFIbYEaIfOdJKngTc6g5cN5JAm0+Bp5rGj9Rr5oOrWVQAQsUxO+r
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: N57iFqvcmprSMr6osAMQbT1dpRFW4iZYGGB4ftR+Cd2co5ctbspGo1B8nY/+91Ua
    on:
      appveyor_repo_tag: true
    artifact: /.*\.nupkg/

artifacts:
  - path: 'nugets\*.nupkg'
