image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: |
      dotnet restore quince.sln
      gitversion /l console /output buildserver /updateassemblyinfo
	  
configuration: Release

build:
  project: quince.sln
  verbosity: minimal

test_script:
  - ps: |
      cd NetworkedPlanet.Quince.Tests
      dotnet test --filter "Category!=GitWrapper"