image: Visual Studio 2017

install:
  - choco install gitversion.portable -y

before_build:
  - gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script:
  - dotnet build
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets NetworkedPlanet.Quince /p:Version=%GitVersion_NugetVersion%

test_script:
  - cd NetworkedPlanet.Quince.Tests
  - dotnet test --filter "Category!=GitWrapper"

deploy:
  - provider: GitHub
    description: 'quince $(GitVersion_SemVer)'
    auth_token:
      secure: lLPsBvR2OxnrgRpVTNWOneUrcR+yK6S1ANE3WbXVJJOIPu3SWt1NCyZ1cexyzy2i
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: kvU+Jp2JbyL0Qt7sSOaQuHtC5L5wG6/Icp6zBUZ+7wuf0Ry26R9MUMMPLtt7a4mU
    on:
      appveyor_repo_tag: true
    artifact: /.*\.nupkg/

artifacts:
  - path: 'nugets\*.nupkg'
