image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script:
  - dotnet build
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets NetworkedPlanet.Quince /p:Version=%GitVersion_NugetVersion%

test_script:
  - cd NetworkedPlanet.Quince.Tests
  - dotnet test --filter "Category!=GitWrapper"

deploy:
  - provider: GitHub
    description: 'quince $(GitVersion_SemVer)'
    auth_token:
      secure: waxwfb392oVPzFIbYEaIfOdJKngTc6g5cN5JAm0+Bp5rGj9Rr5oOrWVQAQsUxO+r
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: 9LbrXgsbg5rAAqBzhM7JSGiJHHG30QBu/MT/ISjOOM6P9R0LqBc2WZibXCUpBh6Q
    on:
      appveyor_repo_tag: true
    artifact: /.*\.nupkg/

artifacts:
  - path: 'nugets\*.nupkg'
